platform :ios, '6.1'

pod 'AFNetworking', '>= 1.1.0'
pod 'CocoaLumberjack', '>= 1.6'
pod 'Objection', '>= 0.15.1'
pod 'MagicalRecord', '>= 2.1'
pod 'AuthKit', :git => 'https://github.com/RCacheaux/AuthKit.git'
pod 'gtm-oauth2', '>= 0.0.1'
